### ISSUE TITLE
menu prob.

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-wordpress-theme#22]
1. if you have some submenus on the edge of the page they get cut off. the best way would be to have them open on the left side when on the edge of the right side of the page

![v31xmankql2ni36bl8ps2w](https://user-images.githubusercontent.com/8138894/32421705-fdcbdbe6-c268-11e7-8acf-ca97a979e157.png)

2. is there a way to have more than 2 submenus?
menu 1
----------sub-menu 2
-----------------------sub-menu 3 (this one don't show same for the rest.)
------------------------------------ sub-menu 4

**Comment by ppfeufer** [comment]
Ya, unfortunately I have no real way to determine if the menu is at the right end of your page or not, so I can't really automatically say that a certain sub-menu should open to the left instead the right. The only current solution is to not have sub-menus on the most right positions. Still looking for a fix, but not to high on my list of things to do.

The menu is limited to 3 levels in total, meaning the top and 2 subs. I had to make that cut somewhere, because for every new level I have to write some CSS rules and so on, which would be to much in the end. If you want more sub-menus, you can handle that with a child theme by adapting the header.php and the CSS to your needs.
