### ISSUE TITLE
Warning on site

### ISSUE THREAD

**Issue by violet-spring** [ppfeufer/eve-online-wordpress-theme#4]
Warning: fsockopen(): unable to connect to eve-api.terra-nanotech.de:8080 (Connection timed out) in /home/sarcosfe/public_html/wp/wp-content/themes/eve-online-wordpress-theme-master/helper/EveApiHelper.php on line 343

I am getting this warning on my site.  I do not have anything configured on the API helper yet.  Is this why?

**Comment by ppfeufer** [comment]
Hmm, that's weird, the API itself is working and shouldn't time out at all.
I am running 2 sites using this theme, no issues so far.

According to the path it seems you are running that on a local test environment? Please check that your system can access that URL. If you pasting the URL into your browser you should land at the EVE Login page. This is because with only the URL without any parameters the EVE API doesn't know what to do. But with this little test you can make sure that the API system can be accessed.

**Comment by violeyspring** [comment]
No it is not a test environment, it's on a hosted site.  How do I enable
the API function so it can be used for people to log in to my site using
their eve login?

**Comment by violeyspring** [comment]
Is there a read me section that will give me info on using the functions of
the API?  I am currently using the miniorange plugin to allow users to
login with EVE SSO.  But does your theme have this built in?  I would also
like to pull peoples corporation info once they log in so I can see their
information from EVE to assign them to groups for my forums.  Is this
possible?

**Comment by ppfeufer** [comment]
All it's used for are some theme internal functions. No SSO Login or other fancy stuff.

**Comment by ppfeufer** [comment]
should be fixed in 08d04deb92bbeb5f5ed7e3b3e331117b99c9fc51

**Comment by violet-spring** [comment]
ok I tried updating the eve api helper and theres a parse error starting on line 14.

**Comment by ppfeufer** [comment]
Please Update the complete theme, not only one file, you may break dependencies.
Also, I need the complete error message if possible.

**Comment by violet-spring** [comment]
Maybe that is the problem, I only updated the file that you changed, so I
probably did the update wrong and caused the problem.  I fixed my issue by
deleting the removed lines and adding the others.  This is my first time
using github, so I'm learning how to use it as I go.

**Comment by ppfeufer** [comment]
This issue should be solved by now. Closing this one.
